title: Algorithms I fell in love with
author: Frenchfaso
twitter: "@frenchfaso"
description: An interactive journey through my algorithmic memories
collections:
  - chapters
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
